### ISSUE TITLE
Buenas Practicas

### ISSUE THREAD

**Issue by Gianotti** [matirey/LabV#1]
https://github.com/matirey/LabV/blob/93fdb6f11a3a6f05c61839eb7ae3017ebc73d2cb/src/Model/Mesa.java#L50

Como crear un mazo
```
List<String> palos = Arrays.asList("Basto", "Copa", "Espada", "Oro");
        List<Card> mazo = new ArrayList<>();
        for (String palo : palos) {
            for (int i = 1; i < 13; i++) {
                mazo.add(new Card(palo, i));
            }
        }
```

**Comment by matirey** [comment]
https://github.com/matirey/LabV/blob/6bcbd4f3fe8e54917827d0b46a4a558be16c7804/src/Model/Mesa.java#L50
Cambié el método como me pediste, solo que usé un iterador (`public interface Iterator<E>`)
``` 
Iterator<String> it= Arrays.asList("Basto","Copa","Espada","Oro").iterator();
        while(it.hasNext()){
           ...
        }
```
